repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: venv

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
        entry: mypy web3_input_decoder/
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        # allow "imported but unused" for pre-commit, forbid it elsewhere e.g. in vscode
        args: ["--config=setup.cfg", "--ignore=E501,E402,F401,E203,W503"]
